<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertials_colors.xacro"/>

    <!-- KONSTANTY >> realne rozmery -->

    <xacro:property name="chassis_length" value="0.195"/>
    <xacro:property name="chassis_width" value="0.140"/>
    <xacro:property name="chassis_height" value="0.05"/>
    <xacro:property name="chassis_mass" value="1.5"/>

    <xacro:property name="main_wheel_radius" value="0.0323"/>
    <xacro:property name="main_wheel_thickness" value="0.026"/>
    <xacro:property name="main_wheel_mass" value="0.1"/>

    <xacro:property name="main_wheel_offset_x" value="0.155"/>
    <xacro:property name="main_wheel_offset_y" value="0.085"/>
    <xacro:property name="main_wheel_offset_z" value="-0.016"/>
    <xacro:property name="caster_wheeel_radius" value="0.015"/>
    <xacro:property name="caster_wheeel_mass" value="0.04"/>
    <xacro:property name="caster_wheeel_offset_x" value="0.015"/>
    <xacro:property name="caster_wheeel_offset_z" value="${main_wheel_offset_z - main_wheel_radius + caster_wheeel_radius}"/>



    <!-- BASE LINK >> stred mezi hlavnimi koli-->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT >> link pro navigaci/lokalizaci -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK >> link na konci uprostred robota -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-main_wheel_offset_x} 0 ${-main_wheel_offset_z}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="gray"/>
        </visual>
        <!-- sloupek k podpurnemu kolecku -->
        <visual>
            <origin xyz="${caster_wheeel_offset_x} 0 ${caster_wheeel_offset_z/2}"/>
            <geometry>
                <box size="${caster_wheeel_offset_x*2} ${caster_wheeel_offset_x*2} ${caster_wheeel_offset_z}"/>
            </geometry>
            <material name="gray"/>
        </visual>
        <!-- valec mezi hlavnimi koly pro simulaci motoru -->
        <visual>
            <origin xyz="${main_wheel_offset_x} 0 ${main_wheel_offset_z}" rpy="${pi/2} 0 0" />
            <geometry>
                <cylinder radius="0.015" length="${chassis_width}"/>
            </geometry>
            <material name="gray"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Gray</material>
    </gazebo>

    <!-- LEFT WHEEL LINK  >> link posunuty od base linku-->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${main_wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <joint name="left_wheel_joint2" type="fixed">
        <parent link="base_link"/>
        <child link="left_wheel2"/>
        <origin xyz="0 ${main_wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
    </joint>

    <!-- atrapa rafku kola, netoci se, jen kvuli vizualu -->

    <link name="left_wheel2">
        <visual>
            <geometry>
                <cylinder radius="0.025" length="${main_wheel_thickness + 0.001}"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>
    <gazebo reference="left_wheel2">
        <material>Gazebo/Blue</material>
    </gazebo>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${main_wheel_radius}" length="${main_wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${main_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${main_wheel_mass}" length="${main_wheel_thickness}" radius="${main_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>




    <!-- RIGHT WHEEL LINK >> link posunuty od base linku-->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-main_wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <joint name="right_wheel_joint2" type="fixed">
        <parent link="base_link"/>
        <child link="right_wheel2"/>
        <origin xyz="0 ${-main_wheel_offset_y} 0" rpy="${pi/2} 0 0" />
    </joint>

    <!-- atrapa rafku kola, netoci se, jen kvuli vizualu -->

    <link name="right_wheel2">
        <visual>
            <geometry>
                <cylinder radius="0.025" length="${main_wheel_thickness + 0.001 }"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>
    <gazebo reference="right_wheel2">
        <material>Gazebo/Blue</material>
    </gazebo>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${main_wheel_radius}" length="${main_wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${main_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${main_wheel_mass}" length="${main_wheel_thickness}" radius="${main_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>


    <!-- CASTER WHEEL LINK >> pomocne kolecko -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheeel_offset_x} 0 ${caster_wheeel_offset_z}"/>
    </joint>


    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheeel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheeel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheeel_mass}" radius="${caster_wheeel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>